export { default as assignmentRoutes } from "./assignment.route";
export { default as authRoutes } from "./auth.route";
export { default as courseRoutes } from "./course.route";
export { default as enrollmentRoutes } from "./enrollment.route";
export { default as sessionRoutes } from "./session.route";
export { default as submissionRoutes } from "./submission.route";
export { default as lessonRoutes } from "./lesson.route";
export { default as lessonMaterialRoutes } from "./lessonMaterial.route";
export { default as lessonProgressRoutes } from "./lessonProgress.route";
export { default as userRoutes } from "./user.route";
export { default as quizQuestionRoutes } from "./quizQuestion.route";
export * from "./major.route";
export * from "./specialist.route";
export * from "./forum.route";
export * from "./subject.route";
