export { default as LandingPage } from "./LandingPage";
export { default as NotFoundPage } from "./NotFound";
export { default as EmailVerifyPage } from "./EmailVerifyPage";
export { default as EmailVerificationPage } from "./EmailVerificationPage";
export { default as ForgotPasswordPage } from "./ForgotPasswordPage";
export { default as ResetPasswordPage } from "./ResetPasswordPage";
export { default as LoginPage } from "./Login";
export { default as RegisterPage } from "./Register";
export { default as DashboardPage } from "./Dashboard";
